const messages = {
  USER_CREATED_SUCCESSFULLY: "User registered successfully.",
  USER_ONBOARDED_SUCCESSFULLY: "User onboarded successfully.",
  FITNESSPROFILE_UPDATED_SUCCESSFULLY: "Fitness profile updated successfully.",
  FITNESSPROFILE_NOT_FOUND: "Fitness profile not found.",
  WORKOUTPLAN_NOT_FOUND: "Workout plan not found.",
  NO_WEEK_SUMMARY_FOUND: "No weekly summaries found.",
  USER_ALREADY_EXISTS: "User already exists.",
  USER_NOT_FOUND: "User not found.",
  NO_WORK_OUT_FOUND: "No workouts found.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  PASSWORD_RESET_SUCCESS: "Password set successfully.",
  INVALID_OLD_PASSWORD: "Invalid old password.",
  PASSWORD_NOT_MATCH: "New password and confirm password do not match.",
  NEW_PASSWORD_SAME_AS_OLD: "New password must be different from the old password.",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully.",
  INTERNAL_SERVER_ERROR: "Something went wrong. Please try again later.",
  UNAUTHORIZED_ACCESS: "Unauthorized access.",
  FORBIDDEN_ACCESS: "You do not have permission to access this resource.",
  DATA_CONFLICT: "Data conflict with existing records.",
  BAD_REQUEST: "Bad request.",
  PASSWORD_NOT_MATCHED: "Passwords do not match.",
  LOGIN_SUCCESSFUL: "Login successful!",
  MISSING_FIELDS: "All fields are required.",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully.",
  OTP_VERIFIED_SUCCESSFULLY: "OTP verified successfully.",
  OTP_RESENT_SUCCESSFULLY: "OTP resent successfully.",
  INVALID_OTP: "Invalid OTP.",
  OTP_RECORD_NOT_FOUND: "OTP record not found.",
  EXPIRED_OTP: "OTP has expired.",
  PASSWORD_RESET_SUCCESSFUL: "Password reset successfully.",
  DETAILS_FETCHED: "Details fetched successfully.",
  PROFILE_UPDATED_SUCCESSFULLY: "User profile updated successfully.",
  GROUP_CREATED_SUCCESSFULLY: "Group created successfully.",
  GROUP_ALREADY_EXISTS: "A group with this name already exists.",
  TOKEN_INVALID_OR_EXPIRED: "Token is invalid or expired.",
  TOKEN_NOT_PROVIDED: "No token provided.",
  INVALID_TOKEN_FORMAT: "Invalid token format.",
  TOKEN_AND_ID_MISMATCH: "Token and user ID do not match.",
  FORGOT_PASSWORD_LINK_SENT: "Password reset link sent to your email.",
  EQUIPMENT_ALREADY_EXIST: "Equipment already exists.",
  EQUIPMENTS_NOT_AVAILABLE: "Equipments not available.",
  EQUIPMENTS_FETCHED_SUCCESSFULLY: "Equipments fetched successfully.",
  WORKOUT_PLAN_GENERATED_SUCCESSFULLY: "Workout plan generated successfully.",
  WORKOUT_PLAN_REGENERATED_SUCCESSFULLY: "Workout plan regenerated successfully.",
  WEEK_SUMMARY_FETCHED: "Weekly summary fetched successfully.",
  TODAY_WORKOUT_FETCHED: "Today's workout fetched successfully.",
  EMAIL_IS_REQUIRED: "Email is required.",
  VALID_DATE: "Workout date must be a valid calendar date.",
  DATE_FORMAT_ERROR: "Invalid date format. Expected format: YYYY-MM-DD.",
  MISSING_WORKOUT_DATE: "Workout date is missing. Expected format: YYYY-MM-DD."
};

export default messages;
